# Generated by Django 3.2.8 on 2021-11-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicChargeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(max_length=20)),
                ('charge_25', models.IntegerField()),
                ('charge_50', models.IntegerField()),
                ('charge_75', models.IntegerField()),
                ('charge_100', models.IntegerField()),
                ('charge_150', models.IntegerField()),
                ('charge_200', models.IntegerField()),
                ('charge_300', models.IntegerField()),
                ('charge_400', models.IntegerField()),
                ('charge_600', models.IntegerField()),
                ('charge_700', models.IntegerField()),
                ('charge_800', models.IntegerField()),
                ('charge_over801', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobanStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_name', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=20)),
            ],
        ),
    ]
