# Generated by Django 3.2.8 on 2021-11-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0002_basicchargemodel_jobanstationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicchargemodel',
            name='charge_type',
        ),
    ]
