# Generated by Django 3.2.8 on 2021-11-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0003_remove_basicchargemodel_charge_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicchargemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='basicchargemodel',
            name='charge_type',
            field=models.CharField(default='スワロー料金', max_length=20, primary_key=True, serialize=False),
        ),
    ]
