# Generated by Django 3.2.8 on 2021-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0004_auto_20211123_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobanstationmodel',
            name='sta_name',
        ),
        migrations.AddField(
            model_name='jobanstationmodel',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobanstationmodel',
            name='name_hr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobanstationmodel',
            name='name_ja',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='basicchargemodel',
            name='charge_type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobanstationmodel',
            name='distance',
            field=models.FloatField(),
        ),
    ]
