# Generated by Django 3.2.8 on 2021-11-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0005_auto_20211123_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='JobanStationModel', # モデル名
            old_name='name_ja',   # 変更前
            new_name='sta_name'    # 変更後
        )
    ]
