# Generated by Django 3.2.8 on 2021-11-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0006_auto_20211124_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='JobanStationModel', # モデル名
            old_name='name_hr',   # 変更前
            new_name='sta_name_hr'    # 変更後
        ),
        migrations.RenameField(
            model_name='JobanStationModel', # モデル名
            old_name='name_en',   # 変更前
            new_name='sta_name_en'    # 変更後
        )
    ]
