# Generated by Django 3.2.8 on 2021-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0007_auto_20211124_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobanstationmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
