# Generated by Django 3.2.8 on 2021-11-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0008_alter_jobanstationmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobanstationmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
