# Generated by Django 3.2.8 on 2021-11-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0010_bacivfaremodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BacivFareModel',
            new_name='BasicFareModel',
        ),
    ]
