# Generated by Django 3.2.8 on 2021-11-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0011_rename_bacivfaremodel_basicfaremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1040',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1080',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1120',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1160',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1200',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1240',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1280',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1320',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1360',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1400',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1440',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1480',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1520',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1560',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1600',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1640',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1680',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1720',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1760',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1800',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1840',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1880',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1920',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_1960',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2040',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2080',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2120',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2160',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2200',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2240',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2280',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2320',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2360',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2400',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2440',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2480',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2520',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2560',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2600',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2640',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2680',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2720',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2760',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2800',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2840',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2880',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2920',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_2960',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_3000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_420',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_440',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_460',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_480',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_500',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_520',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_540',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_560',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_580',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_600',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_640',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_680',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_720',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_760',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_800',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_840',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_880',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_920',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicfaremodel',
            name='fare_960',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_100',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_120',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_140',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_160',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_180',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_200',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_220',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_240',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_260',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_280',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_30',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_300',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_320',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_340',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_35',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_360',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_380',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_40',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_400',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_45',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_50',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_60',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_70',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_80',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicfaremodel',
            name='fare_90',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
