# Generated by Django 3.2.8 on 2021-11-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0013_auto_20211125_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobanstationmodel',
            name='city_area',
        ),
        migrations.RemoveField(
            model_name='jobanstationmodel',
            name='specific_section',
        ),
    ]
