# Generated by Django 3.2.8 on 2021-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0015_auto_20211126_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleDB',
        ),
        migrations.AlterField(
            model_name='jobanstationmodel',
            name='city',
            field=models.CharField(blank=True, choices=[('[札]札幌市内', '札幌市内'), ('[仙]仙台市内', '仙台市内'), ('[区]東京都区内', '東京都区内'), ('[山]東京山手線内', '東京山手線内'), ('[浜]横浜市内', '横浜市内'), ('[名]名古屋市内', '名古屋市内'), ('[京]京都市内', '京都市内'), ('[阪]大阪市内', '大阪市内'), ('[神]神戸市内', '神戸市内'), ('[広]広島市内', '広島市内'), ('[九]北九州市内', '北九州市内'), ('[福]福岡市内', '福岡市内')], max_length=50, null=True),
        ),
    ]
