# Generated by Django 3.2.8 on 2021-12-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_search', '0017_auto_20211205_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanstationmodel',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tokaidostationmodel',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
